on: workflow_dispatch

jobs:

  job1:
    runs-on: ubuntu-latest
    steps: 
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - run: |
          sudo apt install ripgrep
          cd ${{ github.workspace }}
          rg "proxyDNS" ./
      
