on: push

jobs: 
  job1: 
    runs-on: ubuntu-latest
    steps: 
    - run: |
        sudo npm install -g grunt-cli@1.2.0 bower
        cd omega-build
        npm run deps 
        npm run dev 
        grunt
      cd .. 
      ls omega-target-chromium-extension/build/
